export {default as Main} from "./Main"
export {default as Register} from "./Register"
export {default as ProductShop} from "./ProductShop"
export {default as ProtectedRoute} from "./ProtectedRoute"
export {default as Login} from "./Login"